### ISSUE TITLE
":Flog" command fails with "Unknown function: FugitiveIsGitDir"

### ISSUE THREAD

**Issue by bus710** [rbong/vim-flog#110]
Hi, thanks for this amazing plugin! As soon as I saw the nice lines, I had to try.

The title says what my problem is.
My current setup is:
- Debian Trixie
- Nvim 9.1 (AstroNvim 3.6.76)
- vim-fugitive master 572c851
- vim-flog master 58c1d39

<br/>

![2023-09-03_20-12-13](https://github.com/rbong/vim-flog/assets/8920680/8245b760-2f00-45d1-8d5b-0c5d8eff15c2)

<br/>

As the screenshot shows above, I just get the error and nothing happens no matter whatever argument gets passed (-all, -graph, -no-graph). Vim-fugitive works perfectly fine. 

Please let me know if there is anything I can try.

<br/>

**Comment by bus710** [comment]
I found an interesting behavior.
- Cloned a new repository, get into the directory.
- Opened Nvim. 
- Tried the :Flog command. It didn't work and printed the error I shared above.
- Tried the :Floggit or :Flogsplit command. These worked. 
- Then tried the :Flog command again. It did work this time and I could see the nice lines.

I do not know why this happens, but it is working now anyhow.

**Comment by rbong** [comment]
It sounds like Fugitive is being lazy-loaded. Some vim and neovim package managers let you configure plugins to not load until you run certain commands. How are you installing Fugitive? Can you post that part of your `init.vim` or `init.lua` if you're not installing it manually?

**Comment by bus710** [comment]
![SmartSelect_20230904_062444_Chrome](https://github.com/rbong/vim-flog/assets/8920680/e957f126-0d36-4f6c-b526-17420659f20f)

You are right.
I think I missed the line to disable the lazy.nvim's default lazy loading policy.

Thanks!
