### ISSUE TITLE
Guidance on how to change default output format?

### ISSUE THREAD

**Issue by wadcom** [rbong/vim-flog#113]
I'm trying to change the output format of `Flog`. Being an `nvim` newbie I'm lost in where to actually make this change (I've found references to `flog_default_format`, but changing it doesn't seem to affect anything).

I've tried passing the `-format` argument, but it seems to lose colors in the output then...

I think many people come to plugins like `Flog` trying to mimic behavior of their IDEs and having clear instructions on how to achieve this would greatly help.

In my particular case I'd like the output to look something like:

```
•  Add deprecation warning 
[7d862f2] 2023-11-07 13:55:01 (HEAD -> vlad/branch-name)
```

**Comment by wookayin** [comment]
What's the format string you use for [the screenshot in the README](https://github.com/rbong/vim-flog/blob/master/img/screen-graph.png)?

It's apparently not the default one`'%ad [%h] {%an}%d %s'`. (see https://git-scm.com/docs/pretty-formats)

Also highlight is not working very well in general for arbitrary format due to #66.

**Comment by rbong** [comment]
>What's the format string you use for [the screenshot in the README](https://github.com/rbong/vim-flog/blob/master/img/screen-graph.png)?

Looks like `%ad [%h]%d %s`.

Looks also like `-date=short` was used.

Date format is something I haven't mentioned before in this issue. If you like this date format, you can use:

```vim
let g:flog_permanent_default_opts = { 'date': 'short' }
```

>Also highlight is not working very well in general for arbitrary format

If there is something specific that's not working please post it if you can and I will see if I can fix, unless if you're sure it's not fixable in the current system. I want to support as much as I can within the limitations we currently have.
