### ISSUE TITLE
Docs and error messages about deprecated options

### ISSUE THREAD

**Issue by wookayin** [rbong/vim-flog#114]
I see `g:flog_permanent_default_arguments` is now deprecated in favor of `g:flog_permanent_opts`.

There is a problem in the ShowWarning function:
```
  echoerr printf('Deprecated: %s', a:old_usage)
  echoerr printf('New usage: %s', a:new_usage)
```
When called from lua, `echoerr` works like an exception; it throws an annoying error and never executes the following lines. This should have been written like `echom` with `WarningMsg` highlights, so that it does NOT throw.

**Comment by rbong** [comment]
Thanks for reporting, this helped me fix deeper error handling issues too. Should be resolved.

**Comment by wookayin** [comment]
Thanks, I see 3da1d70e65c7f36b9fc771a60e49a3816ad8c54d.
