### ISSUE TITLE
Mapping yy to copy the current revision into the clipboard

### ISSUE THREAD

**Issue by wikimatze** [rbong/vim-flog#12]
I know that there is the `y<C-G>` but I want to directly put the revision into my clipboard with `yy`. Is this possible?

Thanks for that great plugin.

**Comment by rbong** [comment]
To change the binding to `yy`, you can put this in your `.vimrc`:

```vim
autocmd Filetype floggraph nmap <buffer> yy <Plug>FlogYank
autocmd Filetype floggraph vmap <buffer> yy <Plug>FlogYank
```

See [here](https://github.com/rbong/vim-flog/blob/97762d949de517aa90dc324d048429bf78442aa0/ftplugin/floggraph.vim#L34-L90) for the available bindings.

Feel free to reopen if it doesn't work!

**Comment by wikimatze** [comment]
It works, but is it somehow possible to put the content instead of the register into clipboard?

**Comment by rbong** [comment]
@wikimatze `FlogYank` respects the currently selected register, so if you do `"+yy` (or `"*yy` depending on your system) it should copy it into the clipboard. (This will overwrite the unnamed register as well, note that this is normal Vim behaviour unfortunately.)
