### ISSUE TITLE
Running `Flog` with a range that only has start line does not work as expected.

### ISSUE THREAD

**Issue by gh-liu** [rbong/vim-flog#120]
Passing a rage like `:1Flog` does not works as  passing a rage like `:1,1Flog`.

And if `:1Flog` works, maybe `:0Flog` could be like [:0Gclog](https://github.com/tpope/vim-fugitive/blob/master/doc/fugitive.txt#L141) of `vim-fugitive`.

**Comment by rbong** [comment]
Thanks for the bug report and suggestion! Everything should work as you've described now.

**Comment by gh-liu** [comment]
Sorry,I have tried again, still do not work, and I do not see any commit mention this issue, is what the issue described a wrong way to use this plugin?

**Comment by rbong** [comment]
My mistake, I didn't push my changes. It should work now.

**Comment by gh-liu** [comment]
Thanks.
