### ISSUE TITLE
`<ctrl-^>` does not work in the floggraph buffer opened by Flogsplit

### ISSUE THREAD

**Issue by gh-liu** [rbong/vim-flog#122]
0. open whatever a file 
1. run `:Flogsplit` open a floggraph buffer
2. run `:echo expand("#")` will output `flog-0 [uninitialized]` which should be the file name opened in step 0

**Comment by rbong** [comment]
Thanks for reporting. This is fixed in [v3](https://github.com/rbong/vim-flog/issues/135).
