### ISSUE TITLE
Hardcoded Default options

### ISSUE THREAD

**Issue by dgrabla** [rbong/vim-flog#13]
I deal with large repos and I would like to change the `--max-count` default option so I don't need to do `:Flog --max-count` or create a new command. I think at the moment the parameter is only read from the arguments, and there is no way to set a `git log` default command on `flog#build_log_command`. 

Is it possible to change the hardcoded options to variables we can set on the `.vimrc`  on the current version?

```
let g:flog_default_completion = [
      \ '-all ',
      \ '-bisect ',
      \ '-date=',
      \ '-format=',
      \ '-no-merges',
      \ '-skip=',
      \ '-max-count=',
      \ '-open-cmd=',
      \ '-path=',
      \ '-raw-args=',
      \ '-rev='
      \ ]
```

**Comment by rbong** [comment]
It's not yet possible. Thinking about this, the best way is to probably read all default arguments from a dict and deprecate the current options that set individual default arguments. Would that be acceptable?

Example:
```let g:flog_default_arguments = { 'max-count': 9999 }```

Is there anything else that would make large repositories easy to deal with?

Side note: please note that `g:flog_default_completion` is only for use in completion when not currently completing an argument (ex. `-date=%<tab>`). Typically it would be a script variable, but I try to expose as much as possible.

**Comment by dgrabla** [comment]
sure, that would be awesome, thanks!

**Comment by rbong** [comment]
`g:flog_default_arguments` should work after updating. Please let me know if you have any problems.

**Comment by dgrabla** [comment]
It works beautifully, thanks!

For future reference, the default parameter use underscores. 
It should look like this on the .vimrc file:
```
let g:flog_default_arguments = { 'max_count': 500 }
```
