### ISSUE TITLE
Compare branches

### ISSUE THREAD

**Issue by tmnvanderberg** [rbong/vim-flog#131]
Hello and thank you for your work. :)

A common part of my workflow is
```git log --graph BRANCH1..BRANCH2```

(or the equivalent in gitk or GV).

As you probably know this will show the commits that are present in BRANCH2 but not in BRANCH1.

Is there something similar available in Flog?

**Comment by TamaMcGlinn** [comment]
`:Flog -raw-args="BRANCH1..BRANCH2"`

**Comment by rbong** [comment]
You can do it without using raw args:

```
:Flog -rev=BRANCH1..BRANCH2
```

`-rev=` is the same as the positional `<revision-range>` argument to `git log`, and `-path=` is the same as the positional `<path>` argument (can be specified more than once):

```git log [<options>] [<revision-range>] [[--] <path>...]```

Let me know if you have any other questions.
