### ISSUE TITLE
Unknown function ShouldAutoUpdate

### ISSUE THREAD

**Issue by faisal-shah** [rbong/vim-flog#140]
Posting from mobile for (unfortunate) reasons .. apologies in advance for inadequacies in reporting.

I can run :Flog and the graph shows up. When hitting enter on a commit, I get the unknown function error.

**Comment by rbong** [comment]
Previously reported in https://github.com/rbong/vim-flog/issues/139 and should be fixed when you update. Thank you for reporting though!

**Comment by faisal-shah** [comment]
> Previously reported in https://github.com/rbong/vim-flog/issues/139 and should be fixed when you update. Thank you for reporting though!

Apologies for the double report. Thanks for fixing this so quickly!
