### ISSUE TITLE
mini.trailspace only gets disabled in Flog buffer after Ctrl-N or Ctrl-P

### ISSUE THREAD

**Issue by ccjmne** [rbong/vim-flog#142]
Hey,

I'm a *very* new user of vim-flog and am stoked to start using it extensively: thank you for your great project!
I just checked out the new release, 3.0.0 (from a mere few minutes ago!) and am experiencing some issue with `mini.trailspace` with Neovim.

Here's a recording of what I'm experiencing:
[![asciicast](https://asciinema.org/a/pN9b6j0HEMRcZTP4MYr5Nm8Wf.svg)](https://asciinema.org/a/pN9b6j0HEMRcZTP4MYr5Nm8Wf)

Here's a description of what I'm doing in the recording:
- I'm opening Neovim in a playground project
- I enter the `Flog` buffer
- I toggle *all branches* with `A` (the issue also is reproduced without that step, in projects where the history presents lines with a trailing whitespace)
- I move around a bit with `j` and `k`, then with `Ctrl-U` and `Ctrl-D`, and the issue persists
- I start navigating the commits with `Ctrl-N` and Ctrl-P` and the issue immediately goes away.

The previous version I had installed just prior to upgrading to 3.0.0 would exhibit precisely the same issue.

Maybe I am doing something wrong?

Thanks in advance!

**Comment by ccjmne** [comment]
I just noticed that note in the README:

> Highlighting is done only in modifiable buffer by default, only in Normal mode, and stops in Insert mode and when leaving window.

I'm not too sure which buffer that is (sorry, gonna have to do some reading, I'm really *that* new to using this tool), but here's a screenshot showing that the current buffer I see the `mini.trailspace` highlights is indeed not modifiable:

![image](https://github.com/user-attachments/assets/8274d04a-5d39-471f-a75e-8de1a949ffce)

Other than that, I figured the following might be of some relevance:

- `mini.trailspace`'s version is "live" (from `master`, current commit checked out is `d231729`)
- `vim-flog`'s version is at `3.0.0`, commit `e7a0e9f`)

**Comment by ccjmne** [comment]
Ah, of course, I only notice #135 now... my apologies.

**Comment by rbong** [comment]
You're more than welcome to post any new issues as you see fit.

It does appear to be a problem with `mini.trailspace`, we're setting `b:minitrailspace_disabled` as soon as possible. The buffer is not modifiable, but that's after setting the buffer content. See also [this comment](https://github.com/rbong/vim-flog/issues/132#issuecomment-2325305537)

Workaround in `init.lua`:

```lua
vim.api.nvim_create_autocmd(
  "User",
  {
    pattern = { "FlogUpdate" },
    callback = function (ev)
      require("mini.trailspace").unhighlight()
    end,
  }
)
```

**Comment by ccjmne** [comment]
Excellent, thank you very much!
