### ISSUE TITLE
no longer works in git worktree directories

### ISSUE THREAD

**Issue by heytrav** [rbong/vim-flog#144]
For my workflow I checkout my repositories as bare clones under a specific folder `~/repos/bare/project.git` and then create worktrees under another another directory where I do all my work (i.e. `~/code/project/<worktreebranch>`.

This plugin had been working fine in this setup. However since updating yesterday it seems that it now only works in directories that are direct clones (i.e. `git clone git@....../project.git`).

Did something in these recent updates change the way flog figures out it is in a git project?

**Comment by heytrav** [comment]
Pinning my version to v2.1.0 restores functionality.

**Comment by rbong** [comment]
>Did something in these recent updates change the way flog figures out it is in a git project?

Sort of, we're now reducing our reliance on Fugitive to make it easier to integrate other plugins, so some cases might not yet be covered. Sorry about that.

This shouldn't actually impact how it figures out it is in a Git project, but it will impact running commands and finding the root of the project.

>Pinning my version to v2.1.0 restores functionality.

Let me know if pinning to `v3.0.0` restores functionality, that will revert the Fugitive changes but keep all of the other v3 features.

**Comment by heytrav** [comment]
Yes pinning to `v3.0.0` does work!

I originally hadn't specified a version and it was just on the latest `master` commit.

**Comment by heytrav** [comment]
Thanks for the quick reply!

**Comment by rbong** [comment]
No problem. Keeping this open just to track when this is fixed on the master branch, feel free to unsubscribe if you don't want updates for this issue.

**Comment by rbong** [comment]
I fixed a few edge cases, tested with submodules and work trees and it works so far. Let me know if there are any problems.

**Comment by joaodefelipe** [comment]
I believe this might be related (as going back to v3.0.0 also fixes it), but running `:Flog` inside a submodule tree renders the graph for the superproject instead.

**Comment by rbong** [comment]
@joaodefelipe Thank you for reporting. Unfortunately I cannot recreate this.

Opening `:Flog` while the working directory is in the submodule and/or when a file from the submodule is open shows the submodule history. The same is true for the superproject. This seems to work regardless of where the submodule is located.

Please post steps to recreate if you can. This is how I'm trying to recreate it currently:

```
mkdir superproject
cd superproject
git init
mkdir submodule
cd submodule
git init
touch README.md
git add README.md
git commit -m "Initial commit in submodule"
cd ..
git submodule add ./submodule submodule
git commit -m "Add submodule"
```

Please also make sure you are on version `d58ee18` (latest commit on master at time of writing).

**Comment by joaodefelipe** [comment]
My bad. To reproduce it, use the same steps as you outlined above, but run `git submodule absorbgitdirs` at the end.

The resulting layout is what one gets by default after cloning any superproject and running `git submodule update --init --recursive` (or something equivalent). Similarly to a worktree, `superproject/submodule/.git` is a regular file referencing the "real" gitdir.

**Comment by rbong** [comment]
It should be fixed once you update. Thanks again for reporting
