### ISSUE TITLE
git worktree: certain commands cause plugin to crash

### ISSUE THREAD

**Issue by heytrav** [rbong/vim-flog#145]
Follow up from #144 .

After recent updates on master/main branch running `:Flog` now does bring up the git tree as before. However there are a couple issues that I encountered:

* Typing `a` (view all branches) in the viewer just causes the complete viewport to go blank
* Running any other command (i.e. `Floggit fetch`) the viewport crashes and the error dialogue appears `fatal: not a git repository....`

**Comment by rbong** [comment]
Thanks for reporting.

Sorry, I am having problems recreating this. Is the repo this is happening in open source, or are you able to provide a minimal setup (`git` commands that create a repo structure with this issue)?

**Comment by heytrav** [comment]
I have my repos checked out as bare clones in a specific directory:

```
mkdir bare 
mkdir code

cd bare
git clone --bare <some github repo>

cd some-repo.git/

git worktree add --checkout ~/code/project/main  main

cd ~/code/project/main
nvim README.md

:Flog 
# In the Flog viewport
a   # viewport goes blank

```

or 

```
:Flog
:Floggit fetch # viewport crashes and message is displayed: fatal: not a git repository...
```

For this example I was using traefik-helm-chart repo, but it's behaved the same for others that I have from our internal git repositories as well.

**Comment by rbong** [comment]
Thanks again for reporting, I pushed some changes that should handle this case. Please let me know if there are any more issues.
