### ISSUE TITLE
vim-flog not respectign gitconfig

### ISSUE THREAD

**Issue by rodhash** [rbong/vim-flog#152]
Hi

In my `~/.gitconfig` I changed my pager to delta:
```config
[core]
  pager = delta
```

It doesn't affect how vim-flog show the `git diff` .. is this expected?

For instance, when I open any commit to read its details I still see the default git diff.

**Comment by rbong** [comment]
Thanks for the report.

This is expected behaviour. Let me explain. When Flog runs Git commands that open in a new window, it uses Fugitive.

Fugitive opens Git commands in their own Buffer. Vim in this instance is acting as your pager, it's just dumping the output of the command as text and handling the synax and scrolling itself, which is all a pager does.

Delta is a different program from Vim, so for this to work, you would have to run commands in a terminal buffer. Then you wouldn't get some of the benefits of Fugitive like being able to follow objects with `<CR>` and most of your Vim bindings.

Hope that explains things.

**Comment by rodhash** [comment]
Thank you once more for your prompt response and great details!

After digging a little bit I found out there is a way to setup fugitive to work with custom pagers and in fact my fugitive now works with Delta and diff-so-fancy (which I just installed to try it out). So basically my `Git diff` is now using my custom pager.

Flog however seems to not recognize it still, even tho `Git diff` is using my custom pager.

Actually if I run `Floggit` it's able to use my custom pager but running `Flog` which first open the graph and selecting any commit opens up the standard pager (not the custom one).

Any idea how to use the custom pager from Flog's graph?

**Comment by rbong** [comment]
How have you set up Fugitive to use custom pagers?

**Comment by rodhash** [comment]
Actually I didn't, all I did was setting up `pager.diff ` in my git config as explained by Tim Pope [here](https://github.com/tpope/vim-fugitive/issues/2132#issuecomment-1464186541). Now I'm able to just run `Git diff` and it's using my custom pager.

**Comment by rbong** [comment]
Well, today I learned that Fugitive will use terminals for pagers.

Be aware though that not all commands use `Git diff`. What specific bindings are you using?

Any command that starts with `d` or `D` uses `Git diff` internally. But for example `<CR>` uses `Gsplit`, which is a special Fugitive command.

**Comment by rbong** [comment]
Didn't mean to close again

**Comment by rodhash** [comment]
> Didn't mean to close again

No worries!

> Any command that starts with d or D uses Git diff internally. But for example <CR> uses Gsplit, which is a special Fugitive command.

Wow that's it.. Indeed I was using `<cr>` but using other keybindings make use of the custom pager like the ones you mentioned `d` or `D`

**Comment by rodhash** [comment]
thank you and kudos for this amazing project

**Comment by andrey-utkin** [comment]
@rodhash here's what seems to work: in vimrc, put

```
let g:flog_backend_user_split_cmd = 'split term://git show '
```

Then, the magic happens at
https://github.com/rbong/vim-flog/blob/665b16ac8915f746bc43c9572b4581a5e9047216/ftplugin/floggraph.vim#L23

where it appends the object hash (commit in my intention) and executes that instead of `Gsplit`.
