### ISSUE TITLE
Flog doesn't show commits beyond HEAD

### ISSUE THREAD

**Issue by Nelyah** [rbong/vim-flog#18]
Hey, thanks for the great plugin, I really like it!

However I realised that if I checkout to a commit in the log, `HEAD` moves correctly but Flog now only shows commits older than `HEAD`. 

The command I used is `:Floggit checkout <commit hash>`. 
I can still checkout back to master and the Flog is correctly displaying all commits (if master is the most recent commit branch). 
Also, I am using neovim v0.4.2.

Furthermore, this operation (`checkout`) opens a window on the top telling me that I checked out to the commit. It would be great if this output could be either silenced or moved to a preview window so I wouldn't have to manually close it.

**Comment by rbong** [comment]
Alright, preview windows are no longer forced in neovim. It should be fixed if you update. Please let me know if everything is working now.

**Comment by Nelyah** [comment]
> git log --graph, by default, points to the current head. So if you checkout a commit, newer commits will not show up in the log. Some options are to use :Flog -all to enable the --all option, or to press a to toggle showing all commits, or to use :Flog -rev=master if you always want it to point towards a specific target, in this example master.

Awesome! Pardon my lack of knowledge in git. This works great now.

> Can you confirm that it is not closing when you run a :Floggit command or if you press <CR> on a commit?

It seems it is indeed not a preview window on my side. I tried with a minimal config, here are my steps:

    :Flog
    :Floggit checkout <commit hash>
    <c-w>P

And I get the error `E441: There is no preview window`. It closes the window if I `<CR>` the commit however (as there is a vertical split opening for the diff view), but not if I move around or call `:pclose`.

Ps: Just saw that you answered just before me. I'm going to try out the newest version and get back to you.

**Comment by Nelyah** [comment]
Alright, I now get the output in the bottom side of my screen (I think as a message). 

It goes away when I move, so this seems good to me!

**Comment by rbong** [comment]
>And I get the error E441: There is no preview window. It closes the window if I <CR> the commit however (as there is a vertical split opening for the diff view), but not if I move around or call :pclose.

Ahh, I see. You were talking about vim preview windows... I was talking about flog preview windows, which is just a window that closes with flog and closes if you open other commands in preview windows and not an actual vim preview window. I've never thought about how confusing it is to have that duplicate term, my mistake.

The behaviour you were seeing makes a lot more sense to me, so I think that's everything resolved. Going ahead and closing this, thank you for helping improve flog!
