### ISSUE TITLE
Error on ":Flog"

### ISSUE THREAD

**Issue by gavocanov** [rbong/vim-flog#19]
Hi, 

when trying to run flog I get the following error:

```
Error detected while processing function flog#open[10]..flog#open_graph[6]..flog#initialize_graph_buffer[4]..flog#populate_graph_buffer[17]..flog#restore_graph_cursor:
line    1:
E121: Undefined variable: v:t_none
E15: Invalid expression: type(a:cursor) == v:t_none
```

Running neovim without termguicolors in tmux, 16 color custom color scheme (trying to keep things simple here).
After getting the error everything looks fine to me.

Let me know if you need more info and kudos for the nice plugin!!

**Comment by gavocanov** [comment]
Updated to latest version now and it looks like the error is gone, feel free to close the issue.

**Comment by rbong** [comment]
Glad you got it working. Support should be much better going forward because I set up automated tests running in neovim.
