### ISSUE TITLE
Escape Codes in the Output

### ISSUE THREAD

**Issue by jrwrigh** [rbong/vim-flog#24]
```
* ^[[34m2019-11-27 14:17:03 -0700^[[m ^[[33m[b0ee4c4]^[[m ^[[32m{James Wright}^[[m^[[31m (HEAD -> CUBVNC)^[[m Add conda config to .zshrc
* ^[[34m2019-11-24 11:03:02 -0700^[[m ^[[33m[9311f15]^[[m ^[[32m{James Wright}^[[m^[[31m^[[m Add git 2.12.2 to PATH in .zshrc
```
Same exact error as #20, but I can't upgrade git (I don't have permissions to do this).
git version: 2.12.2

Any ideas how I can resolve this without updating git?

**Comment by jrwrigh** [comment]
Using `AnsiEsc` and setting `let g:flog_use_ansi_esc` will successfully remove the escape sequences and color the code. However, the coloring does not match the colorscheme anymore. 

How it looks with `AnsiEsc`:
![image](https://user-images.githubusercontent.com/20801821/77681168-9bcf1100-6f5a-11ea-8668-adfdbf6f82e0.png)

How it normally looks with my normal colorscheme (monokai):
![image](https://user-images.githubusercontent.com/20801821/77681212-a7bad300-6f5a-11ea-8bfb-c386a7cfd62d.png)

**Comment by jrwrigh** [comment]
I added `set notermguicolors` (for unrelated reasons), and the flog output is colored normally:
![image](https://user-images.githubusercontent.com/20801821/77697543-a5fe0900-6f74-11ea-81d4-dedd2772ba4f.png)
 Not terribly ideal honestly.

**Comment by rbong** [comment]
Color markers are included in the default format which cause escape codes in the output in older versions of git even with the `--no-color` or `--color=never` options.

Place the following in your .vimrc to remove the markers altogether:

```vim
    let g:flog_default_arguments = { 'format': '%ad [%h] {%an}%d %s' }
```

**Comment by jrwrigh** [comment]
Brilliant! That works perfectly.

For compatabilities sake, any reason to not have this be in the default arguments?

**Comment by jrwrigh** [comment]
Also, to keep correct with the current syntax highlighting you've defined for the floggraph, the `%ad` should be a `%ai` to enforce the date being ISO format. So

```vim
let g:flog_default_arguments = { 'format': '%ai [%h] {%an}%d %s' }
```

**Comment by rbong** [comment]
>Edit: Or have it check the git version and set the default args appropriately? Admittedly that'd be more complicated and require determining which versions of git are/aren't compatible.

This would be my preferred solution because otherwise I would it would break AnsiEsc support. I just need to know what version this is a problem on. I might not get a chance to investigate for a while.

>Also, to keep correct with the current syntax highlighting you've defined for the floggraph, the %ad should be a %ai to enforce the date being ISO format.

`%ai` is intentional to support custom date formats. To force ISO format with the default format, you can do:

```vim
let g:flog_default_arguments = { 'date': 'iso8601' }
```

See `man git-log` for info about the corresponding `--date` argument.

**Comment by rbong** [comment]
>Brilliant! That works perfectly.

Glad it works by the way - thanks for reporting this issue!
