### ISSUE TITLE
Tab completion of commit hashes no longer working

### ISSUE THREAD

**Issue by jrwrigh** [rbong/vim-flog#25]
I'm not sure if this is a bug or the intended result of the recent changes. Before 692a732 (at least), if I visually selected a series of commits, launched the `Floggit` prompt, and pressed `<Tab>`, I'd get the commits I'd highlighted:

![image](https://user-images.githubusercontent.com/20801821/78909069-31c96800-7a40-11ea-97dc-a27d3a890741.png)

With the latest version, doing the same only brings up the branch names and some files for some reason now:

![image](https://user-images.githubusercontent.com/20801821/78909224-6f2df580-7a40-11ea-8ce2-433bf22ebf3c.png)

Again, this may be the intended effect of the latest changes, but I was just wanting to make sure.

I use this quite a bit since neither fugitive or flog has any shortcut for cherry picking commits.

**Comment by rbong** [comment]
Broke with 3b87d11, should be fixed by e4edbe0

This fixes a lot of other issues too.

Thanks for reporting! Please reopen if the issue persists.
