### ISSUE TITLE
feat: Incremental tab completion

### ISSUE THREAD

**Issue by jrwrigh** [rbong/vim-flog#27]
Example: If I want to checkout `origin/master`, I will habitually type `ori <Tab>` and expect `origin/` to appear the in prompt, but instead the first option in the list of tags shows up. 

I'd expect/like it to work more like tab completion for Ex commands to work, where the minimal amount of text is added to the Ex line, except when a small number of options are available:

In the below example I demonstrate:

1) The behavior of flog
2) Behavior of Ex when many commands match the tab completion (using vim-plug as the example here)
3) Behavior of Ex when only a few (two) commands are available.

![FlogIncrementalTab_20190501](https://user-images.githubusercontent.com/20801821/80807724-279c1480-8b7b-11ea-9424-b991024fb438.gif)

**Comment by rbong** [comment]
I hear you, I do the same thing. The tab completion needs some work. Right now it pulls only from refs it currently holds in the window, which is not a good system. A potential quick fix is to parse and add remotes from branch names but really we need to rework the completion system to pull from real refs.

**Comment by rbong** [comment]
I reworked the argument system and included remotes as part of it. You should now be able to do this:

`git reset --hard o<Tab>/m<Tab>` to complete `:Floggit reset --hard origin/master`

The downside is that remotes have to come before refs on the current line, so if you just want to hit `<Tab>` until you reach refs it will take at least 1 extra tab... can't think of a good way around this right now, open to solutions.

Please open a new ticket if there are any issues (unless if it just doesn't work).
