### ISSUE TITLE
way to flog split horizontally

### ISSUE THREAD

**Issue by roachsinai** [rbong/vim-flog#30]
Could you please tell me the way to let Flog split horizontally, or a command like `FlogHsplit`?

**Comment by rbong** [comment]
`:Flogsplit` opens Flog in a horizontal split, `:vertical Flogsplit` opens it in a vertical split`

**Comment by roachsinai** [comment]
![image](https://user-images.githubusercontent.com/9500049/83872257-33738b80-a764-11ea-9004-9c2bc0d033d6.png)

Thanks for your reply! But I mean the content of right window could be on bottow window(flog on top), it's good to check diff.

**Comment by rbong** [comment]
`:Flogsplitcommit`

Or if you want a binding

```
augroup Flog
  autocmd FileType floggraph nnoremap <buffer> <silent> H :belowright Flogsplitcommit<CR>
augroup END
```

Where `H` is the binding you want.

**Comment by roachsinai** [comment]
Thanks a lot! I use `<CR>` replace `H`, use `BS` map to `vertical Flogsplitcommit`.
