### ISSUE TITLE
Flog checkout branch command don't see branches with paths separator

### ISSUE THREAD

**Issue by PtitCaius** [rbong/vim-flog#31]
When i use Flog's checkout mapping (ie `cob` or `cot`) on a line containing a branch name with path separator in it (ie `feature/someFeature`), Flog can't recognize it, and either fallback for `cob` or raise an error for `cot` (error: pathspec 'someFeature' did not match any file(s) known to git).

I didn't have the time to check the code now, but I'll give a try this weekend.

**Comment by rbong** [comment]
Let me give this a look. Sorry that this flew under my radar.

**Comment by rbong** [comment]
It should be fixed now once you update. Please let me know if there are any problems.
