### ISSUE TITLE
']r' also opens split with diff

### ISSUE THREAD

**Issue by TamaMcGlinn** [rbong/vim-flog#37]
I was surprised to see that ']r' not only jumps to the next reference, but also opens a split with the diff of that commit. Any way I can configure that?

I was convinced this was a bug because I happened to open a repository with only one branch which was up to date with the remote. So ']r' only opened the split diff window, rather than doing nothing as we would otherwise expect.

**Comment by rbong** [comment]
This should map `]r`/`[r` to not open the split:

```vim
au FileType floggraph nnoremap <buffer> <silent> ]r :<C-U>call flog#next_ref()<CR>
au FileType floggraph nnoremap <buffer> <silent> [r :<C-U>call flog#previous_ref()<CR>
```

The [original bindings](https://github.com/rbong/vim-flog/blob/2c3a24af61381b3556153612eadf2bb989c57c21/ftplugin/floggraph.vim#L88-L89) run something like `call flog#next_ref() | vertical belowright Flogsplitcommit`, and `Flogsplitcommit` command causes the bindings to open the commit in a split.

Apologies for not providing a setting specifically for this one thing. Flog's predecessor taught me that there are so many ways to use VIM and Git together that it becomes difficult to provide a setting for everything. Instead I try to provide utility functions to customize behaviour as easily as possible.

If you'd like me to change or provide a utility function, let me know. If you'd like to see all of the functions available, see [autoload/flog.vim](https://github.com/rbong/vim-flog/blob/master/autoload/flog.vim). If you'd like some examples of how commands use these functions, check out [ftplugin/floggraph.vim](https://github.com/rbong/vim-flog/blob/master/ftplugin/floggraph.vim). This effectively serves as the function documentation.

Of course, if you need to know how to do anything else, don't hesitate to comment on this issue or post a new issue. Please also let me know if this doesn't solve your issue.

**Comment by TamaMcGlinn** [comment]
This is great; thank you!
