### ISSUE TITLE
More control over log format

### ISSUE THREAD

**Issue by lervag** [rbong/vim-flog#4]
The default log format is pretty verbose, e.g.:

```
* 2019-03-04 21:53:27 +0100 [6521dd8] {author name} (HEAD -> master, origin/master, origin/HEAD) Fixed #1327: Error in checkhealth
```

I would much prefer if it was possible to customize this to make it shorter, e.g.

```
* [6521dd8] 2019-03-04 Fixed #1327: Error in checkhealth (HEAD -> master, origin/master, origin/HEAD)
```

I am aware of the `-format` argument, but the syntax highlighting seems to be ruined when I use a custom format. I currently use this: ` -raw-args=--date=short -format=[%h]\ %ad\ %s\ %d`, which seems to work quite well.

I don't mind customizing things, but I was thinking it could be sensible to allow two or more styles, e.g. one short style similar to my example (or shorter). And perhaps also improve the syntax matching so it allows different order of elements and matching dates without times and so on.

**Comment by rbong** [comment]
>I was thinking it could be sensible to allow two or more styles

You're right.
I was originally thinking that people can customize syntax regex, but it makes more sense for people who want more narrow matching to do that.
If you pull updates dates using the YYYY-MM-DD format should work.

>And perhaps also improve the syntax matching so it allows different order of elements

Any order of elements should already work for syntax highlighting. I tried the format you posted and it failed because the leading space before the commit was being eaten by the graph syntax group. This should now be fixed.

>--date=short

I will make this supported and add the `-date` option to Flog. You can use it like this:

`:Flog -date=short`

This should be available when you pull updates. Only `short` and `iso861` is currently officially supported, but it won't give errors otherwise.

I've also added some options to make this easier: `g:flog_default_date_format` and `g:flog_default_format`.

If you have any bugs or more ideas please let me know.

**Comment by lervag** [comment]
Great, good work! This makes things much better (IMHO). I'm now looking at multiline formats, and in this case it would be convenient if I could format the date with more "accuracy". E.g., I just modified my settings like this:

```vim
let g:flog_default_format = "[%h] %ad %d\n          %s"

nnoremap <silent><leader>gl :Flog -raw-args=--date=format:'%Y-%m-%d\ %H:%M:%S' -all<cr>
```

For me, this looks good. But I would be happy if I could somehow set something like this to get the same:

```vim
let g:flog_default_format = "[%h] %ad %d\n          %s"
let g:flog_default_date_format = '%Y-%m-%d %H:%M:%S'

nnoremap <silent><leader>gl :Flog -all<cr>
```

I.e., that flog recognizes that I pass in a format string that should be passed on like `--date=format:<string>`. In any case, it is not crucial, and my current setting works anyway.

Finally, I do not quite understand how the bisect mode works. Could you explain how you would use it?

**Comment by rbong** [comment]
>I would be happy if I could somehow set something like this to get the same

That almost works - you just have to put `format:` at the beginning of the string.

```vim
let g:flog_default_date_format = 'format:%Y-%m-%d %H:%M:%S'
```

>Finally, I do not quite understand how the bisect mode works. Could you explain how you would use it?

It passes the `--bisect` flag to `git log`.
All this does is display commits in the log that are part of the current bisection (see `git bisect --help`).

One good bisect workflow is this:

- visually select the range you'd like to bisect
- type in `git bi<tab> start <tab><tab> <tab><tab><tab><CR>` (this will enter in the command `:Floggit bisect start (first commit in selection) (last commit in selection)`)
- you should now be able to see how commits have been marked in the refs section as `refs/bisect/good*` and `refs/bisect/bad*`
- type `gb` to toggle the bisect flag, and the remainder of the commits to explore in the bisection will be displayed
- git bisect commands can be run with `git bi<tab> (command)`, such as `good`, `bad`, `reset` and `skip`

The advantage of doing this in Flog is instant visualization.
I've been doing a couple of things to make it easier, so please update before trying it out.

**Comment by lervag** [comment]
Great, thanks. I think this concludes my feature request, although I guess a minor improvement would be to document the `format:...` version of the `-date` option. The current documentation seems to indicate that it only accepts the `'short'` and `'iso8601'` arguments.

Thanks for the pointer for the bisect workflow. I'll try it out. :)

**Comment by rbong** [comment]
Sorry for the confusion, other date options just won't have syntax highlighting and aren't tested.

**Comment by lervag** [comment]
No problem, and again, thanks!

**Comment by wikimatze** [comment]
@lervag I like your suggestion of the default format with `let g:flog_default_format = "[%h] %ad %d %c %a %s"
` which produces e.g.: `[e035da9] 2018-05-14 16:55:20`. How can I create `[e035da9] 2018-05-14 {author} 16:55:20`?

**Comment by rbong** [comment]
@wikimatze I'm afraid the format you've posted might not be possible. Since you have `{author}` in the middle of the date and time, you have two different custom date formats there. `git-log` only supports passing in one custom date format as far as I know, I don't think you can use that format.

**Comment by wikimatze** [comment]
@rbong thanks for your answer.
