### ISSUE TITLE
[Feature request] Facilitate bindings for git bundle creation

### ISSUE THREAD

**Issue by TamaMcGlinn** [rbong/vim-flog#41]
Part of my workflow has me often creating bundle files using a command like;

```
git bundle create ../filename.bundle master..develop
```

So I would like to create a binding that allows me to visually select two commits and have a bundle be created to update from e.g. master to develop. I have tried this:

```
  autocmd FileType floggraph vno <buffer> cb :<C-U>call flog#run_command("below Git bundle create " . input ("bundle> ") . " %(h'>)..%(h'<)")<CR>
```

But the problem is that, rather than %(h'>) I would need the first local branch pointing at that commit, because currently, `git bundle create` does not accept sha's directly. I've tried some other stuff:

```
  autocmd FileType floggraph vno <buffer> cb :<C-U>call flog#run_command("Git bundle create " . input ("bundle> ") . " %(l'>)..%(l'<)")<CR>
  autocmd FileType floggraph nno <buffer> cb :<C-U>call flog#run_command("Git bundle create " . input ("bundle> ") . " %(h).. --branches --tags")<CR>
```

The normal mode binding works, but the visual one says the bundle would be empty, as if < and > are the wrong way around, but it gives the same error if I swap them around oddly enough.

**Comment by rbong** [comment]
You should now be able to use both `%(b'x)` and `%(l'x)` to get the branch/local branch at the given marks after updating. Let me know if you have any issues.
