### ISSUE TITLE
Is there a way to filter the log by author?

### ISSUE THREAD

**Issue by dusty-phillips** [rbong/vim-flog#43]
I tried g/ to search for the name, but it came back blank.

**Comment by rbong** [comment]
You can do `:Flog -- --author=`, although that's not the best. I will add `-author=`, given that this is so common, but you can use this as a workaround for now.

**Comment by rbong** [comment]
I've added `-author=`. Completion also works (ex. `:Flog -author=<Tab>`, `:Flogsetargs -author=<Tab>`, `:Flog -author=dusty-<Tab>`). Please let me know if there are any problems.

**Comment by dusty-phillips** [comment]
Wow, that was fast and even more than asked for. Excellent customer service. Would buy again. :-)

There's one bug; I have `let g:flog_default_arguments = { 'all': 1, 'date': 'short'}` in my `init.vim` and `:Flog -author=<Tab>` completes correctly, but then fails with 
```
Error detected while processing function flog#open[10]..flog#open_graph[6]..flog#initialize_graph_buffer[4]..flog#populate_graph_buffer[8]..flog#systemlist:
line    3:
fatal: unrecognized argument: --all--author=Dusty Phillips
```
Looks like there's a space missing between `--all` and `--author`

**Comment by rbong** [comment]
Thanks, I have been waiting for an excuse to add this argument, I used `-- --author=...` myself every day so it's been floating around in the back of my head.

My mistake, I added the missing space. It should work now.

**Comment by dusty-phillips** [comment]
Working great! thanks!
