### ISSUE TITLE
Any way to highlight current branch?

### ISSUE THREAD

**Issue by dusty-phillips** [rbong/vim-flog#44]
If I'm looking at this line:

```
* | 2021-01-06 [4a8ca7c] {Some Body} (HEAD -> master, dusty/feature)A commit
```

I don't know whether `master` or `dusty/feature` is currently checked out. I can obviously get it with `git` and then ` branch`, but it'd be cool to have some kind of highlighting (bold or a different colour) right in the log, or a keystroke that jumps to the current branch.

**Comment by rbong** [comment]
Thanks for reporting. The `flogRefHead` highlight group is meant to provide ability to highlight the `HEAD` indicator, which appears next to the currently checked out branch - it was linked to the highlight group `Special`. Just wanted to mention that in case the `Special` group is blending into the `Directory` highlight group, which is what the rest of the ref info should be styled as.

I've now added the `flogRefHeadArrow` and the `flogRefHeadBranch` highlight groups so you can style the arrow after `HEAD` and the name of the currently checked out branch as desired. Just put something similar to the following anywhere in your .vimrc to style the groups (current styling shown):

```vim
highlight default link flogRefHead       Keyword
highlight default link flogRefHeadArrow  flogRef
highlight default link flogRefHeadBranch Special
```

See `:help highlight` for more information on using `:highlight`.

Note that the `flogRefHeadBranch` is now linked to `Special`, so if you couldn't see the `HEAD` highlighting before, you may not be able to see the checked out branch.

Let me know if that works for your use case.

**Comment by dusty-phillips** [comment]
Awesome, that works great! thank you. :)

**Comment by TamaMcGlinn** [comment]
also, if you add something like this in your vimrc, you can jump to the currently checked out commit, which I find very useful (equivalent to Cntrl-Shift-C in GitExtensions)

```
augroup flog
  autocmd FileType floggraph nno <buffer> <silent> <Leader>nc :Flogjump HEAD<CR>
augroup END
```

**Comment by TamaMcGlinn** [comment]
If you're looking for a way to highlight all the commits of a branch, that's [a separate issue](https://github.com/rbong/vim-flog/issues/46).
