### ISSUE TITLE
Use Unicode box-drawing characters for git log view

### ISSUE THREAD

**Issue by TamaMcGlinn** [rbong/vim-flog#49]
[This ~solved~ closed Magit issue](https://github.com/magit/magit/issues/495) would be a great addition to vim-flog's log view. Instead of the disconnected | and * characters, using the right unicode characters we would achieve greater readability.

Two starting points look promising: the graph georgek posted in the Magit issue looks the best, but [the code](https://github.com/georgek/magit-pretty-graph/blob/master/magit-pretty-graph.el) is a little difficult to read and port over; maybe it could be used directly, if we first create a standalone lisp program that outputs that log, and replace the current git command with calling that script.

Alternatively, [this perl script](https://github.com/jwiegley/git-scripts/blob/master/git-forest) doesn't have the colours, but  it has the right characters. Maybe it can be adjusted to just do the right character replacements, and keep vim-flog's colour picking logic.

**Comment by TamaMcGlinn** [comment]
The git command vim-flog uses is built up in flog#build_log_command(), and looks like this:

```
git --git-dir=/home/tama/code/vimplugins/vim-flog/.git log --graph --no-color --pretty='format:__FSTART__%D__FSEP__%h__FSEP____DSTART__%Cblue%ad%Creset
 %C(yellow)[%h]%Creset %Cgreen{%an}%Creset%Cred%d%Creset %s__DEND____FEND__' --date='short' --all
```

forest needs a few modifications to accept the command as-is; it doesn't yet accept the git-dir option, and of course log can be left out. So I would think:

```
forest --no-color --pretty='format:__FSTART__%D__FSEP__%h__FSEP____DSTART__%Cblue%ad%Creset
 %C(yellow)[%h]%Creset %Cgreen{%an}%Creset%Cred%d%Creset %s__DEND____FEND__' --date='short' --all
```

But that currently errors out:

```
		die "vine_commit() did not add this vine.";
```

So I just added a quick `exit(1);` before that line for now, and then added to the end of flog#build_log_command():

```
  let l:command = substitute(l:command, 'git .* log --graph', 'forest', '')
```

woohoo!

![Screenshot from 2021-02-28 21-01-12](https://user-images.githubusercontent.com/5008897/109431770-78cd9c80-7a08-11eb-8789-03b607d4b4c5.png)

**Comment by rbong** [comment]
Here's what I'm thinking to support this change in a relative way:
- Add an option to build your own custom `git log` command
- Add an option to customize how each line is printed (so you can clean up those redundant branch names and dates)
- Customi highlight groups should already be possible (`:autocmd FileType floggraph hi ...` I think)

My thought process is, I don't really want to officially support specific git-log replacement commands but I'm more than willing to provide the tools to do it yourself. Please let me know if these features are satisfactory.

**Comment by rbong** [comment]
Oh yeah, also concerning colors... I could possibly provide a feature to define custom branch characters so they can be highlighted the same way they are currently. I don't particularly like branch coloring, since it's just based on column, so a change like this that lets me visually track branches in a more accurate way would be enough for me. But if you like it, I can add it, just let me know.

**Comment by TamaMcGlinn** [comment]
I was already able to get rid of the redundant branchnames, inside git-forest itself. So now it looks like this:

![Screenshot from 2021-03-03 20-15-25](https://user-images.githubusercontent.com/5008897/109859500-54b6c900-7c5d-11eb-9675-232da6f1fa1d.png)

Indeed, the colours were never very good because of being column based. It took me a while to notice but I think this makes it quite dangerous, actually. You could be mistaken to believe that the colour uniquely identifies the branch, and then scroll down a good deal with e.g. `<C-F><C-F>` and expect a particular commit to be on a particular branch due to the colour of the leading edge from it. So I'm quite happy that they don't work anymore due to using different characters. In the screenshot above you can also see that the date isn't purple due to the dash just prior to it; but I decided to call that a feature; it makes commits that have a reference to them stand out more.

I'm not sure how best to add this option; perhaps a string which, if defined, is passed into substitute? Or, more general would be to allow the user to specify a function that converts a string to another string, but I'm not sure how functors work in vimscript.

I have not been able to find any case where vim-flog really needs that `--git-dir=...` parameter; even a submodule inside a repository elsewhere than the current working directory doesn't trigger incorrect behaviour for me (I omit it entirely, because git-forest doesn't like it).

**Comment by rbong** [comment]
Based on what you've said I will just add an option to customize the git log command. It will be something like `g:flog_get_git_log_command_fn`. I'll pass it the different parts of the log command, as well as some extra data, and it can return a shell command.

It's quite odd that you're not encountering working directory issues regarding `--git-dir`. Flog isn't doing anything to set the working directory for shell commands, so there's no way forest could have enough context to always use the correct git dir. Are you doing anything extra?

I agree that the highlighting can be dangerous, however VIM is only built to highlight code, which typically doesn't involve highlighting these kinds of vertical parallel columns of text that can shift around and cross eachother. Other solutions, like manually setting the highlighting, are extremely slow, and even the ANSII color plugin supported by Flog is quite slow. However it's still the best visual way to draw connections between branches, forest seems to somewhat solve that though.

**Comment by rbong** [comment]
Also apologies but I'll probably fix that highlighting bug. You can always define your own highlight group.

**Comment by rbong** [comment]
I added a new option: `g:flog_build_log_command_fn`. I decided to not have it take any args - it can build up the log command from internal flog functions.

I decided I like `git-forest`, so here's my approach to using it as an example. Your search-and-replace heavy method will also work by calling `flog#build_log_command` instead of the separate functions like I'm doing, this is just a bit more change-proof. Also note that I discovered that you can specify the git dir via environment variables.

```vim
function FlogBuildLog() abort
    let l:state = flog#get_state()

    if l:state.no_graph
        return flog#build_log_command()
    endif

    let l:command = 'export GIT_DIR='
    let l:command .= shellescape(flog#get_fugitive_git_dir())
    let l:command .= '; '

    let l:command .= 'git-forest '
    let l:command .= substitute(flog#build_log_args(), ' --graph', '', '')
    let l:command .= ' -- '
    let l:command .= flog#build_log_paths()

    return l:command
endfunction
let g:flog_build_log_command_fn = 'FlogBuildLog'
```

**Comment by rbong** [comment]
Closing this issue since there's a solution now, please let me know if there are any issues.

**Comment by hoango7604** [comment]
> I was already able to get rid of the redundant branchnames, inside git-forest itself. So now it looks like this:
> 
> ![Screenshot from 2021-03-03 20-15-25](https://user-images.githubusercontent.com/5008897/109859500-54b6c900-7c5d-11eb-9675-232da6f1fa1d.png)
> 
> Indeed, the colours were never very good because of being column based. It took me a while to notice but I think this makes it quite dangerous, actually. You could be mistaken to believe that the colour uniquely identifies the branch, and then scroll down a good deal with e.g. `<C-F><C-F>` and expect a particular commit to be on a particular branch due to the colour of the leading edge from it. So I'm quite happy that they don't work anymore due to using different characters. In the screenshot above you can also see that the date isn't purple due to the dash just prior to it; but I decided to call that a feature; it makes commits that have a reference to them stand out more.
> 
> I'm not sure how best to add this option; perhaps a string which, if defined, is passed into substitute? Or, more general would be to allow the user to specify a function that converts a string to another string, but I'm not sure how functors work in vimscript.
> 
> I have not been able to find any case where vim-flog really needs that `--git-dir=...` parameter; even a submodule inside a repository elsewhere than the current working directory doesn't trigger incorrect behaviour for me (I omit it entirely, because git-forest doesn't like it).

Could you please give me instructions on how to hide redundant branch names inside git-forest. Thank you.

**Comment by TamaMcGlinn** [comment]
Just download [my modified version of git forest here](https://github.com/TamaMcGlinn/dotfiles/blob/master/linuxbash/forest), and put it somewhere accessible to PATH (such as `/usr/bin`). Then configure vim-flog to use that by adding this to your vimrc:

```
function FlogBuildLog() abort
    let l:state = flog#get_state()

    if l:state.no_graph
        return flog#build_log_command()
    endif

    let l:command = 'export GIT_DIR='
    let l:command .= shellescape(flog#get_fugitive_git_dir())
    let l:command .= '; '

    let l:command .= 'forest --style=10'
    let l:command .= substitute(flog#build_log_args(), ' --graph', '', '')
    let l:command .= ' -- '
    let l:command .= flog#build_log_paths()

    return l:command
endfunction

let g:flog_build_log_command_fn = 'FlogBuildLog'
```

**Comment by TamaMcGlinn** [comment]
The modifications I needed for git-forest are visible in [this commit](https://github.com/TamaMcGlinn/dotfiles/commit/3e02f9a1263cfbf055f18d22a887ed041bccef27).

**Comment by hoango7604** [comment]
Thanks @TamaMcGlinn for your rapid response! It worked perfectly. Also I wonder if [git-foresta](https://github.com/takaaki-kasai/git-foresta) could be a replacement for git-forest. I tried to use it but errors occurred (as shown in pictures below). Could you help me with this case please? Thank you for your support!

![Screen Shot 2021-03-30 at 6 10 14 PM](https://user-images.githubusercontent.com/30996727/112979739-2efce100-9183-11eb-9539-83914bd170bf.png)

![Uploading Screen Shot 2021-03-30 at 6.09.21 PM.png…]()

**Comment by TamaMcGlinn** [comment]
I also tried git-foresta and got an error and gave up. It may well have been the very same one, but I'm sorry, I can't be bothered to help you with that, since I find my current fork of git-forest works quite well. The only feature I would still like, git-foresta doesn't have either: [using the forking and merging lines to also display the commit, so that there are no more blank lines.](https://github.com/takaaki-kasai/git-foresta/issues/6)

**Comment by hoango7604** [comment]
@TamaMcGlinn Thank you for spending your time helping me! I really appreciate that!

**Comment by tom-anders** [comment]
@TamaMcGlinn It seems like this does not work with Flog's `-max-count` flag, making it unusable for me in huge repos. Is there any way to fix this?

**Comment by TamaMcGlinn** [comment]
I don't have a full solution; I did start making [vim-instaflog](https://github.com/TamaMcGlinn/vim-instaflog) as a wrapper around a terminal inside of vim which uses unix `less` to limit output, and my initial tests on the linux kernel repo seemed promising but I never really used it, and there were a lot of rough edges (like lines overflowing, and the need to drop into insert mode to scroll down using less). Roger's opinion is that `less` fundamentally can't reduce the runtime, his reasoning is in [this other issue thread](https://github.com/rbong/vim-flog/issues/26), but I never dug into the apparent contradiction between his testresults and mine. Please explore options and let us know.

**Comment by rbong** [comment]
`git-foresta` does not accept a custom format, which means that it will not work with Flog. Flog relies on setting a custom format so it can get certain information about each commit, which it sanitizes from the output.
