### ISSUE TITLE
Add support for git worktrees

### ISSUE THREAD

**Issue by TamaMcGlinn** [rbong/vim-flog#51]
[The motivation](https://www.youtube.com/watch?v=2uEqYw-N8uE&t=60s).

Try it out:

```
git clone [something] --bare
cd something
git worktree add foo
cd foo
```

Now try editing something/foo/bar.txt and then opening vim-flog. It fails with a shell error:

```
Error detected while processing function flogmenu#open_git_log[1]..flog#open[10]..flog#open_graph[6]..flog#initialize_graph_buffer[4]..flog#populate_graph_buffer[9]..flog#systemlist:
/bin/bash: forest: command not found
```

**Comment by TamaMcGlinn** [comment]
Good news! this is strictly only a problem in combination with a custom log command; it can't access the flog state, as needed in the suggested `g:flog_build_log_command_fn` example. Just unlet that and everything seems to work. I'm not sure where to begin with making these two features work together.

**Comment by rbong** [comment]
For me, this doesn't fail with a custom command. Also, `/bin/bash: forest: command not found` does not look like an issue where it can't find the Flog state, it looks more like a problem with your shell not being able to find the executable. If you do `cd foo` then `which forest`, does that work?

**Comment by TamaMcGlinn** [comment]
Thank you; comparing `!echo $PATH` in vim to the output in the terminal led me to the cause, nothing to do with vim-flog.
