### ISSUE TITLE
Opening diff by <CR> on diff line when -path specified doesn't work

### ISSUE THREAD

**Issue by faisal-shah** [rbong/vim-flog#53]
See here for some context: https://github.com/tpope/vim-fugitive/issues/1738

It seems that the pretty format that vim-flog uses is interfering with fugitive.vim's ability to interpret the diff line in a patch log. This happens when you open the patch log with \<TAB> in the floggraph, and not \<CR> .

**Comment by tpope** [comment]
Sounds like a vim-flog problem.

**Comment by tpope** [comment]
And this is on vim-flog so I shouldn't have said anything.

**Comment by rbong** [comment]
I'm leaving this open in case of a more advanced future version or replacement. This would be solved by reducing our reliance on Fugitive, similar to reducing reliance on `git log` like with #46 and #26

**Comment by rbong** [comment]
Workaround:

```vim
autocmd Filetype floggraph nnoremap <buffer> <silent> <Tab> :<C-U>exec flog#Format('vertical belowright Floggit -b -s -t show --format=medium %h -- %p')<CR>
```
