### ISSUE TITLE
Have graph open in whatever split is active

### ISSUE THREAD

**Issue by ganoam** [rbong/vim-flog#58]
Hi! 
Great work, I love the plugin. Thank you!
If I could just ask one thing: Is there a way/ Can there be a way for :Flog to open the graph in whatever split is currently active, instead of taking up the whole screen?
As it is, it tends to mess up my work space. :Flogsplit is a start, but it too requires some fiddling with window commands to get back to my layout.
Cheers,
Noam

**Comment by TamaMcGlinn** [comment]
[Binding](https://github.com/TamaMcGlinn/vimrc/blob/b98c828a9c225729f1421222cda5950d30a28799/git.vim#L103) to `:vertical Flogsplit -all<CR>` works.

**Comment by ganoam** [comment]
Alright, I'll try it out. Thanks man!
