### ISSUE TITLE
Question: show only file names when viewing commits

### ISSUE THREAD

**Issue by RigoTamas** [rbong/vim-flog#59]
Hi,

is it possible, to only show the names of the files when I open a commit with `<CR>`? What I mean by this, is when I type `:Flog`, I get a list of commits. When I hit `<CR>` on a commit, I would like to see the list of files that were modified in that commit, the same way that `:Gitv` showed this.

Also, hitting capital `O` on a modified file opens a diff of that file in a new tab, which is great. This diff mode shows only the relevant parts of the file, that had modifications in it. Is there a way, to expand this diff view, and show the collapsed parts also? If I press `<CR>` on the collapsed lines, it opens a new window with the whole content of the file, instead of just expanding those lines in the same diff view.

Thanks.

**Comment by rbong** [comment]
>is it possible, to only show the names of the files when I open a commit with <CR>?

It is actually possible to do this from Flog:

```
augroup MyFlogSettings
  augroup!
  autocmd FileType floggraph nnoremap <buffer> <silent> <CR> :<C-U>call flog#run_tmp_command('vertical belowright Git show --name-only %h')<CR>
augroup End
```

Note `--name-only`.

>Also, hitting capital O on a modified file opens a diff of that file in a new tab, which is great. This diff mode shows only the relevant parts of the file, that had modifications in it. Is there a way, to expand this diff view, and show the collapsed parts also? If I press <CR> on the collapsed lines, it opens a new window with the whole content of the file, instead of just expanding those lines in the same diff view.

This is however a Fugitive issue. All Flog does is open `:Git show`, we don't add anything to it.

**Comment by RigoTamas** [comment]
Thanks for the quick answers. I solved my first request using this mapping, that I put in my .vimrc:

**Comment by TamaMcGlinn** [comment]
Nice! Thanks for the mapping. Also, `za` is probably the most important thing to remember for folds; toggle the current fold open/closed.

**Comment by rbong** [comment]
Sorry for the long delay.

>`autocmd FileType floggraph nnoremap <buffer> <silent> <CR> :<C-U>call flog#run_tmp_command('vertical belowright Git show %h')<CR> <C-W>l :set foldmethod=syntax<CR> G{j`


This is a potentially easier and more reliable way to run that command:

```vim
call flog#run_tmp_command('vertical belowright Git show %h | set fdm=syntax | normal G{j', 1)
```

It will ensure that the other commands apply in the correct window.
The second option to `run_tmp_command` ensures the window keeps focus.

Not you can also put this in your .vimrc for the setting if you want it to apply everywhere:

```vim
au FileType git set fdm=syntax
```
