### ISSUE TITLE
Bisect workflow seems flawed

### ISSUE THREAD

**Issue by lervag** [rbong/vim-flog#6]
I'm testing the bisect workflow. I do this:

1. In a terminal, I do `git bisect start HEAD HEAD~15`.

2. Start neovim and open the Flog buffer with `nvim` then `:Flog -bisect`.

    ```
    * [54599d8] 2019-03-05 08:11:03 +0100 (origin/master, origin/HEAD, master, refs/bisect/bad)
    * [9801ceb] 2019-02-26 14:51:48 +0100
    * [940f4d5] 2019-02-12 22:58:26 +0100
    * [18cd06e] 2019-02-05 08:57:38 +0100
    * [bfe6aff] 2019-02-04 22:59:31 +0100
    * [4c256f6] 2019-02-01 23:03:37 +0100
    * [fb1c7a9] 2019-02-01 22:56:20 +0100
    * [4210a65] 2019-01-29 09:01:29 +0100
    * [7fcdbd7] 2019-01-25 15:38:54 +0100 (HEAD)
    * [a359564] 2019-01-20 22:51:26 +0100
    * [65d6832] 2019-01-20 09:35:50 +0100
    * [01c2855] 2019-01-11 00:01:49 +0100
    * [ef9af7e] 2019-01-09 13:50:59 +0100
    * [4428d00] 2019-01-07 15:58:14 +0100
    * [4d6466f] 2019-01-06 00:49:55 +0100
    ```

3. Then I do `git bisect good`, I get the following error:

    ```
    Error detected while processing function flog#git[6]..flog#populate_graph_buffer[1]..flog#get_state:
    line    2:
    E605: Exception not caught: flog: could not find state
    ```

    Further, the output of the git command is displayed in a new tab afterwards. If I close this buffer and tab, then I must do `u` for the Flog buffer to update.

----

Expected behaviour after point 3. would be for the git command to occur in the background and for the Flog buffer to update afterwards.

**Comment by rbong** [comment]
The problem is Neovim. When you run a shell command in Vim, the focus is returned after the command is complete. When you run a command in Neovim it's returned earlier, before the shell window is closed. So we expect to be back in the graph window, but we're in a shell window.

I figured this would happen and I thought this would be more of a pain to fix but it turned out to be simple. If you pull, this should now be fixed. Let me know if it's not.

**Comment by lervag** [comment]
Thanks, the error is gone. But I would not really expect the terminal window to persist, which it does for me now. I.e., after `git bisect good`, a new tab is opened and the output of the git command is displayed there. I would expect the command to run basically in the background and to be updated after the command is finished. I still have to manually update with `u`.

**Comment by lervag** [comment]
With Vim, I notice that the git command output is displayed in the terminal, I have to press enter, then it returns to the Flog buffer which is updated as expected. Personally, I would prefer that I did not have to press enter.

**Comment by rbong** [comment]
The terminal persisting, needing input to be closed, is regular vim/neovim `:Git` behaviour from fugitive. Going around fugitive and running commands in the background would be nice, but it's not very Flog-like. Maybe fugitive could support something like `:silent! Git` upstream.

The nice thing about neovim is it has autocommand capabilities after running terminal commands. So, if you're using it, you can do something like `autocmd Termclose * close`.

The buffer not updating, I believe, is an old Neovim issue where it has problems running commands immediately after a terminal command. I've been waiting for them to fix that upstream forever now, so I've just added a `redraw!` statement and that seems to help. Hopefully there aren't any more side effects.

**Comment by lervag** [comment]
Thanks again! I think things now work quite well, and I appreciate your effort on this plugin. I already like it more than gitv which I previouosly used.

**Comment by rbong** [comment]
That's good to hear. A lot of this plugin is just cleaning up the structure so I wasn't sure if it would actually feel better to users. Your feedback is appreciated.
