### ISSUE TITLE
Commit messages that contain parentheses get strange highlighting

### ISSUE THREAD

**Issue by TamaMcGlinn** [rbong/vim-flog#64]
We've both known about this issue a long time, but I always thought it was unavoidable with the way vim's highlighting works. Turns out that's not the case! Have a look at [this fugitive issue](https://github.com/tpope/vim-fugitive/pull/1713), in which various workarounds are implemented by adding special  characters which are then hidden in the buffer. Hopefully we can copy the approach to work for vim-flog.

**Comment by rbong** [comment]
Duplicate of #66 , and I already added more details there
