### ISSUE TITLE
How to exit the search result?

### ISSUE THREAD

**Issue by AchmadFathoni** [rbong/vim-flog#67]
After using `:Flogsetargs -search=xxx` or `:Flogsetargs -patch-search=xxx`, I must close Flog tab and open it again to go back to Flog's default view which shows all commit. Is there any shortcut to do this?

**Comment by rbong** [comment]
You may do `:Flogsetargs -search=` or `:Flogsetargs -patch-search=` to clear the search results. Let me know if that works for you.
