### ISSUE TITLE
Flog -path=% with git-forest look extreme terrible.

### ISSUE THREAD

**Issue by kevinhwang91** [rbong/vim-flog#69]
![image](https://user-images.githubusercontent.com/17562139/137904422-492d593b-128d-4018-a973-cdb0e943c6e2.png)

**Comment by rbong** [comment]
You can fix this by enabling parent rewriting.

Look for this line in your `git-forest` script:

```perl
my($fh, $fhc) = $Repo->command_output_pipe("log", "--date-order",
```

Add the `--parents` option:

```perl
my($fh, $fhc) = $Repo->command_output_pipe("log", "--parents", "--date-order",
```

You can also wait for [this PR](https://github.com/TamaMcGlinn/git-forest/pull/3) to get in if you use this repo.

Details [here](https://github.com/TamaMcGlinn/git-forest/issues/2#issuecomment-1001251708) and [here](https://github.com/TamaMcGlinn/git-forest/issues/2#issuecomment-1001253030).
