### ISSUE TITLE
Key not present in Dictionary: "git_dir"

### ISSUE THREAD

**Issue by AchmadFathoni** [rbong/vim-flog#77]
When executing `Flog` command I get
```
Error detected while processing function flog#open[10]..flog#open_graph[6]..flog#initialize_graph_buffer[2]..flog#trigger_fugitive_git_detection[1]..flog#get_fugitive_git_dir:
line    1:
E716: Key not present in Dictionary: "git_dir"
Press ENTER or type command to continue
```
Tried on two different repositories

**Comment by astier** [comment]
Can confirm.

**Comment by AlterDepp** [comment]
Flog isn't compatible to fugitive since commit 8378b32

**Comment by TamaMcGlinn** [comment]
Yes; reverting that commit in fugitive fixes the issue. To resolve the conflicts, I only needed to remove the conflict markers.

**Comment by AchmadFathoni** [comment]
Here is the working patch for vim-flog. Feel free to make PR

```
diff --git a/autoload/flog.vim b/autoload/flog.vim
index 778da30..8071e2c 100644
--- a/autoload/flog.vim
+++ b/autoload/flog.vim
@@ -187,7 +187,7 @@ function! flog#get_initial_fugitive_repo() abort
 endfunction
 
 function! flog#get_fugitive_workdir() abort
-  return flog#get_state().fugitive_repo.tree()
+  return FugitiveFind(":/")
 endfunction
 
 function! flog#get_fugitive_git_command() abort
@@ -195,7 +195,7 @@ function! flog#get_fugitive_git_command() abort
 endfunction
 
 function! flog#get_fugitive_git_dir() abort
-  return flog#get_state().fugitive_repo.git_dir
+  return FugitiveGitDir()
 endfunction
 
 function! flog#trigger_fugitive_git_detection() abort
```

**Comment by AchmadFathoni** [comment]
#79

**Comment by tpope** [comment]
The above patch always uses the repo for the current buffer, while the API design appears to want to capture the current buffer's repo in `fugitive_repo` and use it later regardless of what buffer is current. Try this:

```diff
diff --git i/autoload/flog.vim w/autoload/flog.vim
index 778da30..b304eb0 100644
--- i/autoload/flog.vim
+++ w/autoload/flog.vim
@@ -170,24 +170,19 @@ endfunction
 " Fugitive interface {{{
 
 function! flog#is_fugitive_buffer() abort
-  try
-    call fugitive#repo()
-  catch /not a Git repository/
-    return v:false
-  endtry
-  return v:true
+  return empty(FugitiveGitDir()) ? v:false : v:true
 endfunction
 
 function! flog#resolve_fugitive_path_arg(path) abort
-  return flog#resolve_path(a:path, fugitive#repo().tree())
+  return flog#resolve_path(a:path, flog#get_fugitive_workdir())
 endfunction
 
 function! flog#get_initial_fugitive_repo() abort
-  return fugitive#repo()
+  return FugitiveGitDir()
 endfunction
 
 function! flog#get_fugitive_workdir() abort
-  return flog#get_state().fugitive_repo.tree()
+  return FugitiveFind(':/', flog#get_state().fugitive_repo)
 endfunction
 
 function! flog#get_fugitive_git_command() abort
@@ -195,7 +190,7 @@ function! flog#get_fugitive_git_command() abort
 endfunction
 
 function! flog#get_fugitive_git_dir() abort
-  return flog#get_state().fugitive_repo.git_dir
+  return FugitiveGitDir(flog#get_state().fugitive_repo)
 endfunction
 
 function! flog#trigger_fugitive_git_detection() abort
```

**Comment by AchmadFathoni** [comment]
> The above patch always uses the repo for the current buffer, while the API design appears to want to capture the current buffer's repo in `fugitive_repo` and use it later regardless of what buffer is current. Try this:
> 
> ```diff
> diff --git i/autoload/flog.vim w/autoload/flog.vim
> index 778da30..b304eb0 100644
> --- i/autoload/flog.vim
> +++ w/autoload/flog.vim
> @@ -170,24 +170,19 @@ endfunction
>  " Fugitive interface {{{
>  
>  function! flog#is_fugitive_buffer() abort
> -  try
> -    call fugitive#repo()
> -  catch /not a Git repository/
> -    return v:false
> -  endtry
> -  return v:true
> +  return empty(FugitiveGitDir()) ? v:false : v:true
>  endfunction
>  
>  function! flog#resolve_fugitive_path_arg(path) abort
> -  return flog#resolve_path(a:path, fugitive#repo().tree())
> +  return flog#resolve_path(a:path, flog#get_fugitive_workdir())
>  endfunction
>  
>  function! flog#get_initial_fugitive_repo() abort
> -  return fugitive#repo()
> +  return FugitiveGitDir()
>  endfunction
>  
>  function! flog#get_fugitive_workdir() abort
> -  return flog#get_state().fugitive_repo.tree()
> +  return FugitiveFind(':/', flog#get_state().fugitive_repo)
>  endfunction
>  
>  function! flog#get_fugitive_git_command() abort
> @@ -195,7 +190,7 @@ function! flog#get_fugitive_git_command() abort
>  endfunction
>  
>  function! flog#get_fugitive_git_dir() abort
> -  return flog#get_state().fugitive_repo.git_dir
> +  return FugitiveFind('.git', flog#get_state().fugitive_repo)
>  endfunction
>  
>  function! flog#trigger_fugitive_git_detection() abort
> ```

Thanks, I've updated my PR

**Comment by rbong** [comment]
Should be fixed, sorry for the delay.
