### ISSUE TITLE
Flog no longer opens due to fugitive change

### ISSUE THREAD

**Issue by meangrape** [rbong/vim-flog#84]
Typing `:Flog` results in the following error. This exception was introduced in `vim-fugitive` commit `02080247` on 2022-06-12. A number of other functions throw related exceptions.

`Error detected while processing function flog#open[10]..flog#open_graph[6]..flog#initialize_graph_buffer[2]..flog#trigger_fugitive_git_detection[2]..flog#get_fugitive_workdir[1]..<SNR>125_repo_tree:`

`E605: Exception not caught: fugitive: fugitive#repo().tree() has been replaced by FugitiveFind(":/")`

**Comment by rbong** [comment]
Flog should be updated to work with fugitive already - see #81. If there are any issues after updating Flog, please post an issue there.
