### ISSUE TITLE
Completion is broken in floggraph window

### ISSUE THREAD

**Issue by jiz4oh** [rbong/vim-flog#92]
<img width="876" alt="image" src="https://user-images.githubusercontent.com/41264693/213921815-046b2ad9-2e49-4c8b-9c65-3c3293afa34a.png">

steps to reproduce:
1. call `:Flog` to open floggraph window
2. call `:Floggit checkout ` 
3. type `<Tab>`

**Comment by rbong** [comment]
Thanks for reporting. I was able to recreate when opening Flog with `:Flog -path=path/to/file`. It should be fixed now.
