### ISSUE TITLE
lua5.4 not supported?

### ISSUE THREAD

**Issue by Shane-XB-Qian** [rbong/vim-flog#95]
```log
echoerr 'flog: warning: only Lua 5.1 and LuaJIT 2.1 are supported'
```

was lua5.4 (default in some distr) not supported?

**Comment by rbong** [comment]
No, only Lua 5.1 and LuaJIT 2.1 are supported.

The reasons for this are:

* LuaJIT is extremely fast (comparable to C) and drawing a graph structure with unbuffered output is expensive
* LuaJIT only supports Lua 5.1
* LuaJIT is built into Neovim

I recommend you install LuaJIT, not use Lua. Use Flog in any decently sized repo and the difference is immediately noticeable.

There are different ways to use LuaJIT. For example:

* Set `:let g:flog_use_internal_lua = false` to not use the version of Lua compiled with Vim (default but recently fixed)
* Set `:let g:flog_lua_bin = "/path/to/my/lua"` to directly set the path to the Lua executable
* The path defaults to just `"luajit"`, you can also set it to a secondary installed version of Lua 5.1 if LuaJIT is not available on your platform
* If you no longer want versions about the version of Lua, set `:let g:flog_check_lua_version = false`
