### ISSUE TITLE
Invalid expression   g:flog_root_dir .. '/lua'

### ISSUE THREAD

**Issue by leoatchina** [rbong/vim-flog#98]
My local laungage is Chinese,   so this error appreared in Chinese, and I tried to translate it into English.
This error was found in vim8.0,  but not in nvim0.8 and vim8.2

![image](https://user-images.githubusercontent.com/4470821/217123341-fadf391f-4ea8-4211-a28e-69dd8ba90ca2.png)

**Comment by rbong** [comment]
Vim 8.0 is not supported, please use Vim 8.2

Sorry for the inconvenience
