### ISSUE TITLE
E117: Unknown function: setcursorcharpos

### ISSUE THREAD

**Issue by durka** [rbong/vim-flog#99]
I'm getting this error whenever I run :Flog or :Flogsplit. After hitting enter the graph seems to load normally though.

```
Error detected while processing function flog#cmd#Flog[19]..flog#floggraph#buf#Update[32]..flog#floggraph#commit#RestorePosition[9]..flog#win#Restore[9]..flog#win#RestoreVcol:
line    2:
E117: Unknown function: setcursorcharpos
```

```
$ nvim --version
NVIM v0.6.1
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by team+vim@tracker.debian.org

Features: +acl +iconv +tui
```

**Comment by rbong** [comment]
I pushed a fix, please let me know if it works. I would recommend upgrading Neovim if at all possible though, 0.6.1 is a bit too old to justify support.

**Comment by durka** [comment]
Oh OK. 0.6.1 is the one included in Ubuntu 22.04 LTS at the moment :/ I
will look into another way to install a newer version

**Comment by durka** [comment]
Seems to have fixed the immediate issue, but now the next undefined function is `virtcol2col`.

**Comment by durka** [comment]
As you mentioned, 0.6.1 is old. I installed Neovim 0.8.3 from homebrew and there are no issues.

**Comment by rbong** [comment]
>Seems to have fixed the immediate issue, but now the next undefined function is virtcol2col.

Sorry about that, if anyone wants to give a shot fixing this issue for older versions of neovim please be my guest. However I think wide char based functions were a lot more limited in older versions, I think you will have to reimplement `virtcol2col`.

**Comment by rbong** [comment]
I had to reimplement all of the wide char functions in v3 to also deal with concealed characters at the same time, so this support issue should pretty much be dead.
